version: '3.8'
services:
  ubuntu:
    build: .
    cap_add: [ SYS_PTRACE ]
    security_opt: [ seccomp:unconfined ]
    volumes:
      - type: bind
        source: $PWD
        target: /app
        consistency: cached # Prevents Docker for Mac bind mounts from being unusably slow.
